### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by koombo** [trust-tree/plant.it#34]
Something new.
You will work here with Mailers :)

I think that for our purposes it will be enoug to use ActionMailer. 
https://guides.rubyonrails.org/action_mailer_basics.html

You have to do few things here, so it will be bigger task. :)

1. Create ContactsController with action 'contact' for example
2. Create Mailer ContactMailer (for example) with some method 
3. Define mail template
4. Set up hardcoded email addresses (for now our emails, later we can create separate one just for this project if you would like to push it to production for real :))
5. Write tests to test sending email from our form etc. Just write tests. :D

**Comment by koombo** [comment]
to do:
- napisać testy dla kontrolera (send_email)
- napisać test dla mailera
- upiększyć formularz
- dodać recaptcha

**Comment by zanetagebka** [comment]
@koombo przykladowy test dla mailera:

```
require 'rails_helper'

RSpec.describe XyzMailer, type: :mailer do
  let(:some_data) { 'for_example_user_email' }

  describe '#contact' do

    it 'sends email blablabla' do
      email = described_class.METHOD_FOR_SPECIFIC_EMAIL

      expect(email.from.first).to eq('')
      expect(email.to.first).to eq('')
      expect(email.subject).to eq('')
      expect(email.body.encoded).to include('')
    end
  end
end
```

Please check in RSpec documentation for what purposes are used `let(:something)`. Take a look at exemplary email test and try to prepare something similar for our mailer. :)
If something is unclear - let me know.
